sudo: false
os:
  - linux
#  - osx
env:
  - TOOLSET=gcc
#  - TOOLSET=darwin
  - TOOLSET=clang
matrix:
  exclude:
    - os: linux
      env: TOOLSET=darwin
    - os: osx
      env: TOOLSET=gcc
language: python
python:
  - "2.6"
#  - "2.7"
install:
  - ./.travis-boost-stage.sh
script:
  - BOOST_BUILD_PATH=/tmp/boost_1_59_0/tools/build /tmp/boost_1_59_0/b2 include=/tmp/boost_1_59_0 library-path=/tmp/boost_1_59_0/stage/lib toolset=${TOOLSET}
